//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banca.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utilizator", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Utilizator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnpField;
        
        private decimal SoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IbanField;
        
        private System.DateTime DataCreareField;
        
        private int IdValutaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUser {
            get {
                return this.IdUserField;
            }
            set {
                if ((this.IdUserField.Equals(value) != true)) {
                    this.IdUserField = value;
                    this.RaisePropertyChanged("IdUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nume {
            get {
                return this.NumeField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeField, value) != true)) {
                    this.NumeField = value;
                    this.RaisePropertyChanged("Nume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Prenume {
            get {
                return this.PrenumeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenumeField, value) != true)) {
                    this.PrenumeField = value;
                    this.RaisePropertyChanged("Prenume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cnp {
            get {
                return this.CnpField;
            }
            set {
                if ((object.ReferenceEquals(this.CnpField, value) != true)) {
                    this.CnpField = value;
                    this.RaisePropertyChanged("Cnp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Sold {
            get {
                return this.SoldField;
            }
            set {
                if ((this.SoldField.Equals(value) != true)) {
                    this.SoldField = value;
                    this.RaisePropertyChanged("Sold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Iban {
            get {
                return this.IbanField;
            }
            set {
                if ((object.ReferenceEquals(this.IbanField, value) != true)) {
                    this.IbanField = value;
                    this.RaisePropertyChanged("Iban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime DataCreare {
            get {
                return this.DataCreareField;
            }
            set {
                if ((this.DataCreareField.Equals(value) != true)) {
                    this.DataCreareField = value;
                    this.RaisePropertyChanged("DataCreare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int IdValuta {
            get {
                return this.IdValutaField;
            }
            set {
                if ((this.IdValutaField.Equals(value) != true)) {
                    this.IdValutaField = value;
                    this.RaisePropertyChanged("IdValuta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Valute", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Valute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdValutaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodValutarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenumireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SimbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaraField;
        
        private double CursdeSchimbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdValuta {
            get {
                return this.IdValutaField;
            }
            set {
                if ((this.IdValutaField.Equals(value) != true)) {
                    this.IdValutaField = value;
                    this.RaisePropertyChanged("IdValuta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodValutar {
            get {
                return this.CodValutarField;
            }
            set {
                if ((object.ReferenceEquals(this.CodValutarField, value) != true)) {
                    this.CodValutarField = value;
                    this.RaisePropertyChanged("CodValutar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Denumire {
            get {
                return this.DenumireField;
            }
            set {
                if ((object.ReferenceEquals(this.DenumireField, value) != true)) {
                    this.DenumireField = value;
                    this.RaisePropertyChanged("Denumire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Simbol {
            get {
                return this.SimbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SimbolField, value) != true)) {
                    this.SimbolField = value;
                    this.RaisePropertyChanged("Simbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tara {
            get {
                return this.TaraField;
            }
            set {
                if ((object.ReferenceEquals(this.TaraField, value) != true)) {
                    this.TaraField = value;
                    this.RaisePropertyChanged("Tara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double CursdeSchimb {
            get {
                return this.CursdeSchimbField;
            }
            set {
                if ((this.CursdeSchimbField.Equals(value) != true)) {
                    this.CursdeSchimbField = value;
                    this.RaisePropertyChanged("CursdeSchimb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name utilizator from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdugareUser", ReplyAction="*")]
        Banca.ServiceReference.AdugareUserResponse AdugareUser(Banca.ServiceReference.AdugareUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdugareUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Banca.ServiceReference.AdugareUserResponse> AdugareUserAsync(Banca.ServiceReference.AdugareUserRequest request);
        
        // CODEGEN: Generating message contract since element name nume from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaUser", ReplyAction="*")]
        Banca.ServiceReference.ModificaUserResponse ModificaUser(Banca.ServiceReference.ModificaUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Banca.ServiceReference.ModificaUserResponse> ModificaUserAsync(Banca.ServiceReference.ModificaUserRequest request);
        
        // CODEGEN: Generating message contract since element name cnp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CautareUser", ReplyAction="*")]
        Banca.ServiceReference.CautareUserResponse CautareUser(Banca.ServiceReference.CautareUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CautareUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Banca.ServiceReference.CautareUserResponse> CautareUserAsync(Banca.ServiceReference.CautareUserRequest request);
        
        // CODEGEN: Generating message contract since element name valuta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdugareValuta", ReplyAction="*")]
        Banca.ServiceReference.AdugareValutaResponse AdugareValuta(Banca.ServiceReference.AdugareValutaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdugareValuta", ReplyAction="*")]
        System.Threading.Tasks.Task<Banca.ServiceReference.AdugareValutaResponse> AdugareValutaAsync(Banca.ServiceReference.AdugareValutaRequest request);
        
        // CODEGEN: Generating message contract since element name denumire from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CautareValuta", ReplyAction="*")]
        Banca.ServiceReference.CautareValutaResponse CautareValuta(Banca.ServiceReference.CautareValutaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CautareValuta", ReplyAction="*")]
        System.Threading.Tasks.Task<Banca.ServiceReference.CautareValutaResponse> CautareValutaAsync(Banca.ServiceReference.CautareValutaRequest request);
        
        // CODEGEN: Generating message contract since element name ToateValuteleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToateValutele", ReplyAction="*")]
        Banca.ServiceReference.ToateValuteleResponse ToateValutele(Banca.ServiceReference.ToateValuteleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToateValutele", ReplyAction="*")]
        System.Threading.Tasks.Task<Banca.ServiceReference.ToateValuteleResponse> ToateValuteleAsync(Banca.ServiceReference.ToateValuteleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdugareUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdugareUser", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.AdugareUserRequestBody Body;
        
        public AdugareUserRequest() {
        }
        
        public AdugareUserRequest(Banca.ServiceReference.AdugareUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdugareUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Banca.ServiceReference.Utilizator utilizator;
        
        public AdugareUserRequestBody() {
        }
        
        public AdugareUserRequestBody(Banca.ServiceReference.Utilizator utilizator) {
            this.utilizator = utilizator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdugareUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdugareUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.AdugareUserResponseBody Body;
        
        public AdugareUserResponse() {
        }
        
        public AdugareUserResponse(Banca.ServiceReference.AdugareUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdugareUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdugareUserResult;
        
        public AdugareUserResponseBody() {
        }
        
        public AdugareUserResponseBody(bool AdugareUserResult) {
            this.AdugareUserResult = AdugareUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificaUser", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.ModificaUserRequestBody Body;
        
        public ModificaUserRequest() {
        }
        
        public ModificaUserRequest(Banca.ServiceReference.ModificaUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificaUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefon;
        
        public ModificaUserRequestBody() {
        }
        
        public ModificaUserRequestBody(int id_user, string nume, string prenume, string telefon) {
            this.id_user = id_user;
            this.nume = nume;
            this.prenume = prenume;
            this.telefon = telefon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificaUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.ModificaUserResponseBody Body;
        
        public ModificaUserResponse() {
        }
        
        public ModificaUserResponse(Banca.ServiceReference.ModificaUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificaUserResponseBody {
        
        public ModificaUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareUser", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.CautareUserRequestBody Body;
        
        public CautareUserRequest() {
        }
        
        public CautareUserRequest(Banca.ServiceReference.CautareUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CautareUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cnp;
        
        public CautareUserRequestBody() {
        }
        
        public CautareUserRequestBody(string cnp) {
            this.cnp = cnp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.CautareUserResponseBody Body;
        
        public CautareUserResponse() {
        }
        
        public CautareUserResponse(Banca.ServiceReference.CautareUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CautareUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Banca.ServiceReference.Utilizator CautareUserResult;
        
        public CautareUserResponseBody() {
        }
        
        public CautareUserResponseBody(Banca.ServiceReference.Utilizator CautareUserResult) {
            this.CautareUserResult = CautareUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdugareValutaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdugareValuta", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.AdugareValutaRequestBody Body;
        
        public AdugareValutaRequest() {
        }
        
        public AdugareValutaRequest(Banca.ServiceReference.AdugareValutaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdugareValutaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Banca.ServiceReference.Valute valuta;
        
        public AdugareValutaRequestBody() {
        }
        
        public AdugareValutaRequestBody(Banca.ServiceReference.Valute valuta) {
            this.valuta = valuta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdugareValutaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdugareValutaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.AdugareValutaResponseBody Body;
        
        public AdugareValutaResponse() {
        }
        
        public AdugareValutaResponse(Banca.ServiceReference.AdugareValutaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdugareValutaResponseBody {
        
        public AdugareValutaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareValutaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareValuta", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.CautareValutaRequestBody Body;
        
        public CautareValutaRequest() {
        }
        
        public CautareValutaRequest(Banca.ServiceReference.CautareValutaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CautareValutaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string denumire;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string simbol;
        
        public CautareValutaRequestBody() {
        }
        
        public CautareValutaRequestBody(string denumire, string simbol) {
            this.denumire = denumire;
            this.simbol = simbol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareValutaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareValutaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.CautareValutaResponseBody Body;
        
        public CautareValutaResponse() {
        }
        
        public CautareValutaResponse(Banca.ServiceReference.CautareValutaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CautareValutaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CautareValutaResult;
        
        public CautareValutaResponseBody() {
        }
        
        public CautareValutaResponseBody(int CautareValutaResult) {
            this.CautareValutaResult = CautareValutaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToateValuteleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToateValutele", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.ToateValuteleRequestBody Body;
        
        public ToateValuteleRequest() {
        }
        
        public ToateValuteleRequest(Banca.ServiceReference.ToateValuteleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ToateValuteleRequestBody {
        
        public ToateValuteleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToateValuteleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToateValuteleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.ToateValuteleResponseBody Body;
        
        public ToateValuteleResponse() {
        }
        
        public ToateValuteleResponse(Banca.ServiceReference.ToateValuteleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ToateValuteleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Banca.ServiceReference.ArrayOfString ToateValuteleResult;
        
        public ToateValuteleResponseBody() {
        }
        
        public ToateValuteleResponseBody(Banca.ServiceReference.ArrayOfString ToateValuteleResult) {
            this.ToateValuteleResult = ToateValuteleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Banca.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Banca.ServiceReference.WebServiceSoap>, Banca.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Banca.ServiceReference.AdugareUserResponse Banca.ServiceReference.WebServiceSoap.AdugareUser(Banca.ServiceReference.AdugareUserRequest request) {
            return base.Channel.AdugareUser(request);
        }
        
        public bool AdugareUser(Banca.ServiceReference.Utilizator utilizator) {
            Banca.ServiceReference.AdugareUserRequest inValue = new Banca.ServiceReference.AdugareUserRequest();
            inValue.Body = new Banca.ServiceReference.AdugareUserRequestBody();
            inValue.Body.utilizator = utilizator;
            Banca.ServiceReference.AdugareUserResponse retVal = ((Banca.ServiceReference.WebServiceSoap)(this)).AdugareUser(inValue);
            return retVal.Body.AdugareUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Banca.ServiceReference.AdugareUserResponse> Banca.ServiceReference.WebServiceSoap.AdugareUserAsync(Banca.ServiceReference.AdugareUserRequest request) {
            return base.Channel.AdugareUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Banca.ServiceReference.AdugareUserResponse> AdugareUserAsync(Banca.ServiceReference.Utilizator utilizator) {
            Banca.ServiceReference.AdugareUserRequest inValue = new Banca.ServiceReference.AdugareUserRequest();
            inValue.Body = new Banca.ServiceReference.AdugareUserRequestBody();
            inValue.Body.utilizator = utilizator;
            return ((Banca.ServiceReference.WebServiceSoap)(this)).AdugareUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Banca.ServiceReference.ModificaUserResponse Banca.ServiceReference.WebServiceSoap.ModificaUser(Banca.ServiceReference.ModificaUserRequest request) {
            return base.Channel.ModificaUser(request);
        }
        
        public void ModificaUser(int id_user, string nume, string prenume, string telefon) {
            Banca.ServiceReference.ModificaUserRequest inValue = new Banca.ServiceReference.ModificaUserRequest();
            inValue.Body = new Banca.ServiceReference.ModificaUserRequestBody();
            inValue.Body.id_user = id_user;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.telefon = telefon;
            Banca.ServiceReference.ModificaUserResponse retVal = ((Banca.ServiceReference.WebServiceSoap)(this)).ModificaUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Banca.ServiceReference.ModificaUserResponse> Banca.ServiceReference.WebServiceSoap.ModificaUserAsync(Banca.ServiceReference.ModificaUserRequest request) {
            return base.Channel.ModificaUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Banca.ServiceReference.ModificaUserResponse> ModificaUserAsync(int id_user, string nume, string prenume, string telefon) {
            Banca.ServiceReference.ModificaUserRequest inValue = new Banca.ServiceReference.ModificaUserRequest();
            inValue.Body = new Banca.ServiceReference.ModificaUserRequestBody();
            inValue.Body.id_user = id_user;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.telefon = telefon;
            return ((Banca.ServiceReference.WebServiceSoap)(this)).ModificaUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Banca.ServiceReference.CautareUserResponse Banca.ServiceReference.WebServiceSoap.CautareUser(Banca.ServiceReference.CautareUserRequest request) {
            return base.Channel.CautareUser(request);
        }
        
        public Banca.ServiceReference.Utilizator CautareUser(string cnp) {
            Banca.ServiceReference.CautareUserRequest inValue = new Banca.ServiceReference.CautareUserRequest();
            inValue.Body = new Banca.ServiceReference.CautareUserRequestBody();
            inValue.Body.cnp = cnp;
            Banca.ServiceReference.CautareUserResponse retVal = ((Banca.ServiceReference.WebServiceSoap)(this)).CautareUser(inValue);
            return retVal.Body.CautareUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Banca.ServiceReference.CautareUserResponse> Banca.ServiceReference.WebServiceSoap.CautareUserAsync(Banca.ServiceReference.CautareUserRequest request) {
            return base.Channel.CautareUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Banca.ServiceReference.CautareUserResponse> CautareUserAsync(string cnp) {
            Banca.ServiceReference.CautareUserRequest inValue = new Banca.ServiceReference.CautareUserRequest();
            inValue.Body = new Banca.ServiceReference.CautareUserRequestBody();
            inValue.Body.cnp = cnp;
            return ((Banca.ServiceReference.WebServiceSoap)(this)).CautareUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Banca.ServiceReference.AdugareValutaResponse Banca.ServiceReference.WebServiceSoap.AdugareValuta(Banca.ServiceReference.AdugareValutaRequest request) {
            return base.Channel.AdugareValuta(request);
        }
        
        public void AdugareValuta(Banca.ServiceReference.Valute valuta) {
            Banca.ServiceReference.AdugareValutaRequest inValue = new Banca.ServiceReference.AdugareValutaRequest();
            inValue.Body = new Banca.ServiceReference.AdugareValutaRequestBody();
            inValue.Body.valuta = valuta;
            Banca.ServiceReference.AdugareValutaResponse retVal = ((Banca.ServiceReference.WebServiceSoap)(this)).AdugareValuta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Banca.ServiceReference.AdugareValutaResponse> Banca.ServiceReference.WebServiceSoap.AdugareValutaAsync(Banca.ServiceReference.AdugareValutaRequest request) {
            return base.Channel.AdugareValutaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Banca.ServiceReference.AdugareValutaResponse> AdugareValutaAsync(Banca.ServiceReference.Valute valuta) {
            Banca.ServiceReference.AdugareValutaRequest inValue = new Banca.ServiceReference.AdugareValutaRequest();
            inValue.Body = new Banca.ServiceReference.AdugareValutaRequestBody();
            inValue.Body.valuta = valuta;
            return ((Banca.ServiceReference.WebServiceSoap)(this)).AdugareValutaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Banca.ServiceReference.CautareValutaResponse Banca.ServiceReference.WebServiceSoap.CautareValuta(Banca.ServiceReference.CautareValutaRequest request) {
            return base.Channel.CautareValuta(request);
        }
        
        public int CautareValuta(string denumire, string simbol) {
            Banca.ServiceReference.CautareValutaRequest inValue = new Banca.ServiceReference.CautareValutaRequest();
            inValue.Body = new Banca.ServiceReference.CautareValutaRequestBody();
            inValue.Body.denumire = denumire;
            inValue.Body.simbol = simbol;
            Banca.ServiceReference.CautareValutaResponse retVal = ((Banca.ServiceReference.WebServiceSoap)(this)).CautareValuta(inValue);
            return retVal.Body.CautareValutaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Banca.ServiceReference.CautareValutaResponse> Banca.ServiceReference.WebServiceSoap.CautareValutaAsync(Banca.ServiceReference.CautareValutaRequest request) {
            return base.Channel.CautareValutaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Banca.ServiceReference.CautareValutaResponse> CautareValutaAsync(string denumire, string simbol) {
            Banca.ServiceReference.CautareValutaRequest inValue = new Banca.ServiceReference.CautareValutaRequest();
            inValue.Body = new Banca.ServiceReference.CautareValutaRequestBody();
            inValue.Body.denumire = denumire;
            inValue.Body.simbol = simbol;
            return ((Banca.ServiceReference.WebServiceSoap)(this)).CautareValutaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Banca.ServiceReference.ToateValuteleResponse Banca.ServiceReference.WebServiceSoap.ToateValutele(Banca.ServiceReference.ToateValuteleRequest request) {
            return base.Channel.ToateValutele(request);
        }
        
        public Banca.ServiceReference.ArrayOfString ToateValutele() {
            Banca.ServiceReference.ToateValuteleRequest inValue = new Banca.ServiceReference.ToateValuteleRequest();
            inValue.Body = new Banca.ServiceReference.ToateValuteleRequestBody();
            Banca.ServiceReference.ToateValuteleResponse retVal = ((Banca.ServiceReference.WebServiceSoap)(this)).ToateValutele(inValue);
            return retVal.Body.ToateValuteleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Banca.ServiceReference.ToateValuteleResponse> Banca.ServiceReference.WebServiceSoap.ToateValuteleAsync(Banca.ServiceReference.ToateValuteleRequest request) {
            return base.Channel.ToateValuteleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Banca.ServiceReference.ToateValuteleResponse> ToateValuteleAsync() {
            Banca.ServiceReference.ToateValuteleRequest inValue = new Banca.ServiceReference.ToateValuteleRequest();
            inValue.Body = new Banca.ServiceReference.ToateValuteleRequestBody();
            return ((Banca.ServiceReference.WebServiceSoap)(this)).ToateValuteleAsync(inValue);
        }
    }
}
