//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banca.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name iban from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdugareUser", ReplyAction="*")]
        Banca.ServiceReference.AdugareUserResponse AdugareUser(Banca.ServiceReference.AdugareUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdugareUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Banca.ServiceReference.AdugareUserResponse> AdugareUserAsync(Banca.ServiceReference.AdugareUserRequest request);
        
        // CODEGEN: Generating message contract since element name nume from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaUser", ReplyAction="*")]
        Banca.ServiceReference.ModificaUserResponse ModificaUser(Banca.ServiceReference.ModificaUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Banca.ServiceReference.ModificaUserResponse> ModificaUserAsync(Banca.ServiceReference.ModificaUserRequest request);
        
        // CODEGEN: Generating message contract since element name iban from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CautareUser", ReplyAction="*")]
        Banca.ServiceReference.CautareUserResponse CautareUser(Banca.ServiceReference.CautareUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CautareUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Banca.ServiceReference.CautareUserResponse> CautareUserAsync(Banca.ServiceReference.CautareUserRequest request);
        
        // CODEGEN: Generating message contract since element name cod_valutar from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdugareValuta", ReplyAction="*")]
        Banca.ServiceReference.AdugareValutaResponse AdugareValuta(Banca.ServiceReference.AdugareValutaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdugareValuta", ReplyAction="*")]
        System.Threading.Tasks.Task<Banca.ServiceReference.AdugareValutaResponse> AdugareValutaAsync(Banca.ServiceReference.AdugareValutaRequest request);
        
        // CODEGEN: Generating message contract since element name cod_valutar from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CautareValuta", ReplyAction="*")]
        Banca.ServiceReference.CautareValutaResponse CautareValuta(Banca.ServiceReference.CautareValutaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CautareValuta", ReplyAction="*")]
        System.Threading.Tasks.Task<Banca.ServiceReference.CautareValutaResponse> CautareValutaAsync(Banca.ServiceReference.CautareValutaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdugareUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdugareUser", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.AdugareUserRequestBody Body;
        
        public AdugareUserRequest() {
        }
        
        public AdugareUserRequest(Banca.ServiceReference.AdugareUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdugareUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal sold;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string iban;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cnp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string telefon;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime data_creare;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int id_valuta;
        
        public AdugareUserRequestBody() {
        }
        
        public AdugareUserRequestBody(decimal sold, string iban, string nume, string prenume, string cnp, string telefon, System.DateTime data_creare, int id_valuta) {
            this.sold = sold;
            this.iban = iban;
            this.nume = nume;
            this.prenume = prenume;
            this.cnp = cnp;
            this.telefon = telefon;
            this.data_creare = data_creare;
            this.id_valuta = id_valuta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdugareUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdugareUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.AdugareUserResponseBody Body;
        
        public AdugareUserResponse() {
        }
        
        public AdugareUserResponse(Banca.ServiceReference.AdugareUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdugareUserResponseBody {
        
        public AdugareUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificaUser", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.ModificaUserRequestBody Body;
        
        public ModificaUserRequest() {
        }
        
        public ModificaUserRequest(Banca.ServiceReference.ModificaUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificaUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefon;
        
        public ModificaUserRequestBody() {
        }
        
        public ModificaUserRequestBody(int id_user, string nume, string prenume, string telefon) {
            this.id_user = id_user;
            this.nume = nume;
            this.prenume = prenume;
            this.telefon = telefon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificaUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.ModificaUserResponseBody Body;
        
        public ModificaUserResponse() {
        }
        
        public ModificaUserResponse(Banca.ServiceReference.ModificaUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificaUserResponseBody {
        
        public ModificaUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareUser", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.CautareUserRequestBody Body;
        
        public CautareUserRequest() {
        }
        
        public CautareUserRequest(Banca.ServiceReference.CautareUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CautareUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string iban;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prenume;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cnp;
        
        public CautareUserRequestBody() {
        }
        
        public CautareUserRequestBody(string iban, string nume, string prenume, string cnp) {
            this.iban = iban;
            this.nume = nume;
            this.prenume = prenume;
            this.cnp = cnp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.CautareUserResponseBody Body;
        
        public CautareUserResponse() {
        }
        
        public CautareUserResponse(Banca.ServiceReference.CautareUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CautareUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CautareUserResult;
        
        public CautareUserResponseBody() {
        }
        
        public CautareUserResponseBody(int CautareUserResult) {
            this.CautareUserResult = CautareUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdugareValutaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdugareValuta", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.AdugareValutaRequestBody Body;
        
        public AdugareValutaRequest() {
        }
        
        public AdugareValutaRequest(Banca.ServiceReference.AdugareValutaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdugareValutaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cod_valutar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string denumire;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string simbol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tara;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double curs_de_schimb;
        
        public AdugareValutaRequestBody() {
        }
        
        public AdugareValutaRequestBody(string cod_valutar, string denumire, string simbol, string tara, double curs_de_schimb) {
            this.cod_valutar = cod_valutar;
            this.denumire = denumire;
            this.simbol = simbol;
            this.tara = tara;
            this.curs_de_schimb = curs_de_schimb;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdugareValutaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdugareValutaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.AdugareValutaResponseBody Body;
        
        public AdugareValutaResponse() {
        }
        
        public AdugareValutaResponse(Banca.ServiceReference.AdugareValutaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdugareValutaResponseBody {
        
        public AdugareValutaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareValutaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareValuta", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.CautareValutaRequestBody Body;
        
        public CautareValutaRequest() {
        }
        
        public CautareValutaRequest(Banca.ServiceReference.CautareValutaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CautareValutaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cod_valutar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string denumire;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string simbol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tara;
        
        public CautareValutaRequestBody() {
        }
        
        public CautareValutaRequestBody(string cod_valutar, string denumire, string simbol, string tara) {
            this.cod_valutar = cod_valutar;
            this.denumire = denumire;
            this.simbol = simbol;
            this.tara = tara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CautareValutaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CautareValutaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Banca.ServiceReference.CautareValutaResponseBody Body;
        
        public CautareValutaResponse() {
        }
        
        public CautareValutaResponse(Banca.ServiceReference.CautareValutaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CautareValutaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CautareValutaResult;
        
        public CautareValutaResponseBody() {
        }
        
        public CautareValutaResponseBody(int CautareValutaResult) {
            this.CautareValutaResult = CautareValutaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Banca.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Banca.ServiceReference.WebServiceSoap>, Banca.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Banca.ServiceReference.AdugareUserResponse Banca.ServiceReference.WebServiceSoap.AdugareUser(Banca.ServiceReference.AdugareUserRequest request) {
            return base.Channel.AdugareUser(request);
        }
        
        public void AdugareUser(decimal sold, string iban, string nume, string prenume, string cnp, string telefon, System.DateTime data_creare, int id_valuta) {
            Banca.ServiceReference.AdugareUserRequest inValue = new Banca.ServiceReference.AdugareUserRequest();
            inValue.Body = new Banca.ServiceReference.AdugareUserRequestBody();
            inValue.Body.sold = sold;
            inValue.Body.iban = iban;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.cnp = cnp;
            inValue.Body.telefon = telefon;
            inValue.Body.data_creare = data_creare;
            inValue.Body.id_valuta = id_valuta;
            Banca.ServiceReference.AdugareUserResponse retVal = ((Banca.ServiceReference.WebServiceSoap)(this)).AdugareUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Banca.ServiceReference.AdugareUserResponse> Banca.ServiceReference.WebServiceSoap.AdugareUserAsync(Banca.ServiceReference.AdugareUserRequest request) {
            return base.Channel.AdugareUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Banca.ServiceReference.AdugareUserResponse> AdugareUserAsync(decimal sold, string iban, string nume, string prenume, string cnp, string telefon, System.DateTime data_creare, int id_valuta) {
            Banca.ServiceReference.AdugareUserRequest inValue = new Banca.ServiceReference.AdugareUserRequest();
            inValue.Body = new Banca.ServiceReference.AdugareUserRequestBody();
            inValue.Body.sold = sold;
            inValue.Body.iban = iban;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.cnp = cnp;
            inValue.Body.telefon = telefon;
            inValue.Body.data_creare = data_creare;
            inValue.Body.id_valuta = id_valuta;
            return ((Banca.ServiceReference.WebServiceSoap)(this)).AdugareUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Banca.ServiceReference.ModificaUserResponse Banca.ServiceReference.WebServiceSoap.ModificaUser(Banca.ServiceReference.ModificaUserRequest request) {
            return base.Channel.ModificaUser(request);
        }
        
        public void ModificaUser(int id_user, string nume, string prenume, string telefon) {
            Banca.ServiceReference.ModificaUserRequest inValue = new Banca.ServiceReference.ModificaUserRequest();
            inValue.Body = new Banca.ServiceReference.ModificaUserRequestBody();
            inValue.Body.id_user = id_user;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.telefon = telefon;
            Banca.ServiceReference.ModificaUserResponse retVal = ((Banca.ServiceReference.WebServiceSoap)(this)).ModificaUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Banca.ServiceReference.ModificaUserResponse> Banca.ServiceReference.WebServiceSoap.ModificaUserAsync(Banca.ServiceReference.ModificaUserRequest request) {
            return base.Channel.ModificaUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Banca.ServiceReference.ModificaUserResponse> ModificaUserAsync(int id_user, string nume, string prenume, string telefon) {
            Banca.ServiceReference.ModificaUserRequest inValue = new Banca.ServiceReference.ModificaUserRequest();
            inValue.Body = new Banca.ServiceReference.ModificaUserRequestBody();
            inValue.Body.id_user = id_user;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.telefon = telefon;
            return ((Banca.ServiceReference.WebServiceSoap)(this)).ModificaUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Banca.ServiceReference.CautareUserResponse Banca.ServiceReference.WebServiceSoap.CautareUser(Banca.ServiceReference.CautareUserRequest request) {
            return base.Channel.CautareUser(request);
        }
        
        public int CautareUser(string iban, string nume, string prenume, string cnp) {
            Banca.ServiceReference.CautareUserRequest inValue = new Banca.ServiceReference.CautareUserRequest();
            inValue.Body = new Banca.ServiceReference.CautareUserRequestBody();
            inValue.Body.iban = iban;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.cnp = cnp;
            Banca.ServiceReference.CautareUserResponse retVal = ((Banca.ServiceReference.WebServiceSoap)(this)).CautareUser(inValue);
            return retVal.Body.CautareUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Banca.ServiceReference.CautareUserResponse> Banca.ServiceReference.WebServiceSoap.CautareUserAsync(Banca.ServiceReference.CautareUserRequest request) {
            return base.Channel.CautareUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Banca.ServiceReference.CautareUserResponse> CautareUserAsync(string iban, string nume, string prenume, string cnp) {
            Banca.ServiceReference.CautareUserRequest inValue = new Banca.ServiceReference.CautareUserRequest();
            inValue.Body = new Banca.ServiceReference.CautareUserRequestBody();
            inValue.Body.iban = iban;
            inValue.Body.nume = nume;
            inValue.Body.prenume = prenume;
            inValue.Body.cnp = cnp;
            return ((Banca.ServiceReference.WebServiceSoap)(this)).CautareUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Banca.ServiceReference.AdugareValutaResponse Banca.ServiceReference.WebServiceSoap.AdugareValuta(Banca.ServiceReference.AdugareValutaRequest request) {
            return base.Channel.AdugareValuta(request);
        }
        
        public void AdugareValuta(string cod_valutar, string denumire, string simbol, string tara, double curs_de_schimb) {
            Banca.ServiceReference.AdugareValutaRequest inValue = new Banca.ServiceReference.AdugareValutaRequest();
            inValue.Body = new Banca.ServiceReference.AdugareValutaRequestBody();
            inValue.Body.cod_valutar = cod_valutar;
            inValue.Body.denumire = denumire;
            inValue.Body.simbol = simbol;
            inValue.Body.tara = tara;
            inValue.Body.curs_de_schimb = curs_de_schimb;
            Banca.ServiceReference.AdugareValutaResponse retVal = ((Banca.ServiceReference.WebServiceSoap)(this)).AdugareValuta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Banca.ServiceReference.AdugareValutaResponse> Banca.ServiceReference.WebServiceSoap.AdugareValutaAsync(Banca.ServiceReference.AdugareValutaRequest request) {
            return base.Channel.AdugareValutaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Banca.ServiceReference.AdugareValutaResponse> AdugareValutaAsync(string cod_valutar, string denumire, string simbol, string tara, double curs_de_schimb) {
            Banca.ServiceReference.AdugareValutaRequest inValue = new Banca.ServiceReference.AdugareValutaRequest();
            inValue.Body = new Banca.ServiceReference.AdugareValutaRequestBody();
            inValue.Body.cod_valutar = cod_valutar;
            inValue.Body.denumire = denumire;
            inValue.Body.simbol = simbol;
            inValue.Body.tara = tara;
            inValue.Body.curs_de_schimb = curs_de_schimb;
            return ((Banca.ServiceReference.WebServiceSoap)(this)).AdugareValutaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Banca.ServiceReference.CautareValutaResponse Banca.ServiceReference.WebServiceSoap.CautareValuta(Banca.ServiceReference.CautareValutaRequest request) {
            return base.Channel.CautareValuta(request);
        }
        
        public int CautareValuta(string cod_valutar, string denumire, string simbol, string tara) {
            Banca.ServiceReference.CautareValutaRequest inValue = new Banca.ServiceReference.CautareValutaRequest();
            inValue.Body = new Banca.ServiceReference.CautareValutaRequestBody();
            inValue.Body.cod_valutar = cod_valutar;
            inValue.Body.denumire = denumire;
            inValue.Body.simbol = simbol;
            inValue.Body.tara = tara;
            Banca.ServiceReference.CautareValutaResponse retVal = ((Banca.ServiceReference.WebServiceSoap)(this)).CautareValuta(inValue);
            return retVal.Body.CautareValutaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Banca.ServiceReference.CautareValutaResponse> Banca.ServiceReference.WebServiceSoap.CautareValutaAsync(Banca.ServiceReference.CautareValutaRequest request) {
            return base.Channel.CautareValutaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Banca.ServiceReference.CautareValutaResponse> CautareValutaAsync(string cod_valutar, string denumire, string simbol, string tara) {
            Banca.ServiceReference.CautareValutaRequest inValue = new Banca.ServiceReference.CautareValutaRequest();
            inValue.Body = new Banca.ServiceReference.CautareValutaRequestBody();
            inValue.Body.cod_valutar = cod_valutar;
            inValue.Body.denumire = denumire;
            inValue.Body.simbol = simbol;
            inValue.Body.tara = tara;
            return ((Banca.ServiceReference.WebServiceSoap)(this)).CautareValutaAsync(inValue);
        }
    }
}
